spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/loree_db
    username: postgres
    password: '***'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
